services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: recipe_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"

  backend:
    build: .
    container_name: recipe_backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app    # 로컬 현재 디렉토리를 컨테이너 /app에 마운트
      - /app/node_modules  # node_modules는 컨테이너 안에서 유지
    command: npm run dev
    depends_on:
      - mysql
